import { useEffect,useMemo,useRef,useState } from "react";
import type { CSSProperties,ReactNode } from "react";
import "./scroll-scrub.css";
export interface ScrollScrubScene{id:string;label:string;poster:string;mobilePoster?:string;clip:string;mobileClip?:string;title:string;body:string;kicker?:string;tags?:string[];actions?:ReactNode;align?:"left"|"right";scroll?:number;linger?:number;objectPosition?:string;mobileObjectPosition?:string}
export interface ScrollScrubConnector{poster:string;mobilePoster?:string;clip:string;mobileClip?:string;scroll?:number}
export interface ScrollScrubTheme{background:string;ink:string;muted:string;accent:string}
export interface ScrollScrubProps{scenes:ScrollScrubScene[];connectors?:(ScrollScrubConnector|null)[];theme:ScrollScrubTheme;className?:string;onActiveSectionChange?:(index:number)=>void}
type Seg={key:string;kind:"scene"|"connector";sectionIndex:number;nextSectionIndex:number;poster:string;mobilePoster?:string;clip:string;mobileClip?:string;weight:number;linger:number;objectPosition:string;mobileObjectPosition:string;scene?:ScrollScrubScene};
type Run=Seg&{band:HTMLElement;layer:HTMLElement;start:number;end:number;current:number;target:number;visible:boolean;loading:boolean;ready:boolean;failed:boolean;loadedSource?:string;video?:HTMLVideoElement};
type ThemeStyle=CSSProperties&Record<`--ss-${string}`,string|number>;
const clamp=(v:number,min=0,max=1)=>Math.min(max,Math.max(min,v));
const smooth=(v:number)=>{const x=clamp(v);return x*x*(3-2*x)};
const linger=(v:number,a:number)=>{const x=clamp(v),l=clamp(a,0,.6),c=x-.5;return(1-l)*x+l*(4*c**3+.5)};
function build(scenes:ScrollScrubScene[],connectors:(ScrollScrubConnector|null)[]):Seg[]{const r:Seg[]=[];scenes.forEach((s,i)=>{if(s.mobileClip&&!s.mobilePoster)throw new Error(`Scene ${s.id} needs mobilePoster`);r.push({clip:s.clip,key:`scene:${s.id}`,kind:"scene",linger:s.linger??0,mobileClip:s.mobileClip,mobilePoster:s.mobilePoster,mobileObjectPosition:s.mobileObjectPosition??s.objectPosition??"50% 50%",nextSectionIndex:i,objectPosition:s.objectPosition??"50% 50%",poster:s.poster,scene:s,sectionIndex:i,weight:s.scroll??1.4});const c=connectors[i];if(i<scenes.length-1&&c?.clip){const n=scenes[i+1];r.push({clip:c.clip,key:`connector:${s.id}:${n.id}`,kind:"connector",linger:0,mobileClip:c.mobileClip,mobilePoster:c.mobilePoster,mobileObjectPosition:n.mobileObjectPosition??n.objectPosition??"50% 50%",nextSectionIndex:i+1,objectPosition:n.objectPosition??"50% 50%",poster:c.poster,sectionIndex:i,weight:c.scroll??.8})}});return r}
export function ScrollScrub({scenes,connectors,theme,className,onActiveSectionChange}:ScrollScrubProps){
const rootRef=useRef<HTMLElement>(null),activeRef=useRef(onActiveSectionChange),[activeSection,setActiveSection]=useState(0),segments=useMemo(()=>build(scenes,connectors??[]),[scenes,connectors]);
useEffect(()=>{activeRef.current=onActiveSectionChange},[onActiveSectionChange]);
useEffect(()=>{const root=rootRef.current;if(!root||!segments.length)return;const layers=[...root.querySelectorAll<HTMLElement>("[data-scroll-scrub-layer]")],bands=[...root.querySelectorAll<HTMLElement>("[data-scroll-scrub-band]")];if(layers.length!==segments.length||bands.length!==segments.length)throw new Error("ScrollScrub markup mismatch");
const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches,coarse=matchMedia("(hover: none) and (pointer: coarse)").matches,small=matchMedia("(max-width: 860px)"),mobile=()=>coarse||small.matches,source=(s:Run)=>mobile()&&s.mobileClip?s.mobileClip:s.clip;
const run:Run[]=segments.map((s,i)=>({...s,band:bands[i],layer:layers[i],start:0,end:0,current:0,target:0,visible:i===0,loading:false,ready:false,failed:false}));
let destroyed=false,dirty=true,frame=0,rootTop=0,total=1,vh=innerHeight,width=innerWidth,active=-1;
const unload=(s:Run)=>{if(s.video){s.video.pause();s.video.removeAttribute("src");s.video.load();s.video.remove()}delete s.video;delete s.loadedSource;s.loading=false;s.ready=false;s.failed=false;delete s.layer.dataset.videoPainted};
const layout=()=>{const py=scrollY||pageYOffset;rootTop=root.getBoundingClientRect().top+py;vh=innerHeight;width=innerWidth;run.forEach(s=>{if(s.loadedSource&&s.loadedSource!==source(s))unload(s);const rect=s.band.getBoundingClientRect();s.start=rect.top+py-rootTop;s.end=s.start+rect.height});total=Math.max(run.at(-1)?.end??vh,vh);dirty=true};
const load=(s:Run)=>{const src=source(s);if(reduce||destroyed||s.loading||s.ready||s.failed||!src)return;s.loading=true;s.loadedSource=src;const v=document.createElement("video");v.className="scroll-scrub__video";v.muted=true;v.defaultMuted=true;v.playsInline=true;v.preload="auto";v.setAttribute("muted","");v.setAttribute("playsinline","");v.src=src;v.addEventListener("loadedmetadata",()=>{if(s.video!==v)return;s.ready=true;s.loading=false;try{v.currentTime=Math.max(.001,clamp(s.target,0,.999)*(v.duration||1))}catch{}dirty=true},{once:true});v.addEventListener("loadeddata",()=>{if(s.video===v)s.layer.dataset.videoPainted="true"},{once:true});v.addEventListener("seeked",()=>{if(s.video===v)s.layer.dataset.videoPainted="true"});v.addEventListener("error",()=>{if(s.video!==v)return;s.failed=true;s.loading=false;s.ready=false;s.layer.dataset.videoFailed="true"},{once:true});s.layer.append(v);s.video=v;v.load()};
const read=()=>{const y=clamp((scrollY||pageYOffset)-rootTop,0,total),fade=.1*vh;let ci=0;run.forEach((s,i)=>{if(y>=s.start)ci=i;const len=Math.max(s.end-s.start,1),local=clamp((y-s.start)/len);s.target=s.linger?linger(local,s.linger):local;let out=y<s.start?s.start-y:y>s.end?y-s.end:0;const op=reduce?(out===0?1:0):smooth(1-out/Math.max(fade,1));s.visible=op>.001;s.layer.style.opacity=String(op);s.layer.style.zIndex=i===ci?"2":"1";if(y>s.start-2.5*vh&&y<s.end+1.5*vh)load(s)});const c=run[ci],p=clamp((y-c.start)/Math.max(c.end-c.start,1)),next=c.kind==="connector"&&p>=.5?c.nextSectionIndex:c.sectionIndex;if(next!==active){active=next;setActiveSection(active);activeRef.current?.(active)}root.style.setProperty("--ss-progress",String(clamp(y/total)))};
const update=()=>run.forEach(s=>{const v=s.video;if(!v||!s.ready||v.seeking)return;s.current+=(s.target-s.current)*.38;const t=clamp(s.current,0,.999)*(v.duration||1),eps=mobile()?.018:.008;if(Math.abs(v.currentTime-t)>eps)try{v.currentTime=t}catch{}});
const tick=()=>{if(destroyed)return;if(dirty){dirty=false;read()}update();frame=requestAnimationFrame(tick)},onScroll=()=>{dirty=true},onResize=()=>{if(coarse&&innerWidth===width)return;layout()};
addEventListener("scroll",onScroll,{passive:true});addEventListener("resize",onResize);addEventListener("orientationchange",layout);layout();if(run[0])load(run[0]);frame=requestAnimationFrame(tick);
return()=>{destroyed=true;cancelAnimationFrame(frame);removeEventListener("scroll",onScroll);removeEventListener("resize",onResize);removeEventListener("orientationchange",layout);run.forEach(unload)}},[segments]);
if(!scenes.length)return null;const st:ThemeStyle={"--ss-accent":theme.accent,"--ss-bg":theme.background,"--ss-ink":theme.ink,"--ss-muted":theme.muted};
return <section className={["scroll-scrub",className].filter(Boolean).join(" ")} ref={rootRef} style={st}><div className="scroll-scrub__stage"><div aria-hidden="true" className="scroll-scrub__media">{segments.map((s,i)=><figure className={`scroll-scrub__layer scroll-scrub__layer--${s.kind}`} data-scroll-scrub-layer="" key={s.key} style={{"--ss-mobile-position":s.mobileObjectPosition,"--ss-object-position":s.objectPosition} as ThemeStyle}><picture className="scroll-scrub__picture">{s.mobilePoster&&<source media="(hover: none) and (pointer: coarse), (max-width: 860px)" srcSet={s.mobilePoster}/>}<img alt="" className="scroll-scrub__poster" decoding="async" fetchPriority={i===0?"high":"auto"} loading={i===0?"eager":"lazy"} src={s.poster}/></picture></figure>)}</div><div aria-hidden="true" className="scroll-scrub__progress"><span/></div></div><div className="scroll-scrub__story">{segments.map(s=>s.kind==="connector"?<div aria-hidden="true" className="scroll-scrub__connector-band" data-scroll-scrub-band="" key={s.key} style={{minHeight:`${Math.max(s.weight,.2)*100}dvh`}}/>:<article className="scroll-scrub__chapter" data-align={s.scene?.align??"left"} data-scroll-scrub-band="" id={s.scene?.id} key={s.key} style={{minHeight:`${Math.max(s.weight,.2)*100}dvh`}}><div className="scroll-scrub__chapter-pin"><div className="scroll-scrub__copy">{s.scene?.kicker&&<p className="scroll-scrub__kicker">{s.scene.kicker}</p>}<h1 className="scroll-scrub__title">{s.scene?.title}</h1><p className="scroll-scrub__body">{s.scene?.body}</p>{s.scene?.tags?.length?<ul className="scroll-scrub__tags">{s.scene.tags.map(t=><li key={t}>{t}</li>)}</ul>:null}</div></div></article>)}</div></section>
}
